"""
Rollout Replay Buffer for DOTS-RR

This module implements the FIFO replay buffer that stores recent rollouts
for reuse in subsequent training steps, reducing per-step computation cost.

Key Concepts:
=============

1. WHY REPLAY?
   - Rollout generation is expensive (~47-54% of per-step time)
   - By reusing recent rollouts, we reduce fresh rollout generation
   - Fresh rollouts: δ·B questions
   - Replayed rollouts: (1-δ)·B questions
   - With δ=0.5, we cut rollout generation time by ~50%

2. WHAT TO STORE?
   - Complete rollout data (not just questions):
     * input_ids, attention_mask (token sequences)
     * old_log_probs (behavior policy probabilities - CRITICAL for PPO/GRPO)
     * rewards, advantages
     * question index, text, solution
   - Why store log_probs? They define the "behavior policy" π_old
     that generated these rollouts. The GRPO ratio π_θ/π_old needs this.

3. BUFFER RULES:
   a) FIFO Eviction: When capacity exceeded, remove oldest entries
   b) Deduplication: Keep only most recent rollouts per question
      (prevents same question appearing multiple times)
   c) Informative Filter: Only store rollouts where avg_reward ∈ (0, 1)
      (all-0 or all-1 rewards give zero gradient signal)

4. OFF-POLICY CONSIDERATION:
   - Replayed samples are "off-policy" (generated by older policy)
   - PPO/GRPO clipping naturally handles this
   - FIFO ensures samples don't get too stale
   - No explicit importance sampling weights needed (paper's approach)

Reference:
    ASTRAL implementation: ray_trainer_teacher_replay.py
    https://github.com/ASTRAL-Group/data-efficient-llm-rl/
"""

from typing import Optional, List, Tuple, Dict
import torch
import numpy as np
from data_proto import DataProto


class ReplayBuffer:
    """
    FIFO Replay Buffer with deduplication and informative sample filtering.

    This buffer stores complete rollout data (DataProto objects) and provides
    methods to add new rollouts, sample for replay, and manage capacity.

    Attributes:
        capacity: Maximum number of question-groups to store
        group_size: Number of rollouts per question (G)
        filter_informative: Whether to filter for informative samples
        buffer: The underlying DataProto storage (or None if empty)

    Example:
        >>> buffer = ReplayBuffer(capacity=512, group_size=8)
        >>> buffer.add(fresh_rollouts)  # Add new rollouts
        >>> replay_batch = buffer.sample(num_samples=128)  # Sample for replay
        >>> combined = DataProto.concat([fresh_batch, replay_batch])
    """

    def __init__(
        self,
        capacity: int = 512,
        group_size: int = 8,
        filter_informative: bool = True,
        replay_strategy: str = "random"
    ):
        """
        Initialize the replay buffer.

        Args:
            capacity: Maximum number of questions (not individual rollouts).
                     Total rollouts stored = capacity * group_size
            group_size: Number of rollouts per question (G parameter)
            filter_informative: If True, only store rollouts where
                               avg_reward is strictly between 0 and 1
            replay_strategy: How to select samples for replay
                           "random" - uniform random selection
                           "fifo" - oldest first (least recent)
        """
        self.capacity = capacity
        self.group_size = group_size
        self.filter_informative = filter_informative
        self.replay_strategy = replay_strategy

        # Internal storage - starts empty
        self.buffer: Optional[DataProto] = None

        # Track question indices for deduplication
        self._question_indices: Dict[int, int] = {}  # question_id -> buffer_position

    def __len__(self) -> int:
        """Return number of question-groups in buffer."""
        if self.buffer is None:
            return 0
        return len(self.buffer) // self.group_size

    @property
    def num_rollouts(self) -> int:
        """Return total number of individual rollouts."""
        if self.buffer is None:
            return 0
        return len(self.buffer)

    def is_ready(self, required_samples: int) -> bool:
        """
        Check if buffer has enough samples for replay.

        Args:
            required_samples: Number of questions needed for replay batch

        Returns:
            True if buffer has at least required_samples questions
        """
        return len(self) >= required_samples

    def add(self, data: DataProto) -> int:
        """
        Add new rollouts to the buffer.

        This method:
        1. Filters for informative samples (if enabled)
        2. Adds to buffer
        3. Deduplicates (keeps most recent per question)
        4. Truncates to capacity (FIFO eviction)

        Args:
            data: DataProto containing rollouts to add.
                 Must have 'index' in non_tensor_batch for deduplication.
                 Must have 'rewards' in batch for informative filtering.

        Returns:
            Number of question-groups actually added (after filtering)

        Example:
            >>> # After generating fresh rollouts
            >>> num_added = buffer.add(fresh_rollouts)
            >>> print(f"Added {num_added} question-groups to buffer")
        """
        if len(data) == 0:
            return 0

        # Step 1: Filter for informative samples (optional)
        if self.filter_informative:
            data = self._filter_informative(data)
            if len(data) == 0:
                return 0

        # Step 2: Add to buffer
        if self.buffer is None:
            self.buffer = data
        else:
            self.buffer = DataProto.concat([self.buffer, data])

        # Step 3: Deduplicate
        self._deduplicate()

        # Step 4: FIFO truncation to capacity
        num_before = len(self)
        self._truncate_to_capacity()
        num_after = len(self)

        return len(data) // self.group_size

    def _filter_informative(self, data: DataProto) -> DataProto:
        """
        Filter to keep only informative rollouts.

        A question-group is "informative" if its average reward is strictly
        between 0 and 1. This means:
        - At least one rollout succeeded (reward=1)
        - At least one rollout failed (reward=0)
        - Therefore, the advantage computation will have variance
        - Therefore, there will be a non-zero gradient signal

        If all rollouts have the same reward (all 0 or all 1), the
        advantage A_i = r_i - mean(r) = 0 for all i, giving zero gradient.

        Args:
            data: DataProto with 'rewards' tensor

        Returns:
            DataProto containing only informative question-groups
        """
        if "rewards" not in data.batch:
            return data

        rewards = data.batch["rewards"]
        n_rollouts = len(data)
        n_questions = n_rollouts // self.group_size

        # Compute average reward per question-group
        rewards_grouped = rewards.view(n_questions, self.group_size)
        avg_rewards = rewards_grouped.mean(dim=1)

        # Informative = avg_reward strictly between 0 and 1
        informative_mask = (avg_rewards > 0) & (avg_rewards < 1)

        if not informative_mask.any():
            return DataProto()  # Empty

        # Expand mask to cover all rollouts in each group
        expanded_mask = informative_mask.repeat_interleave(self.group_size)

        return data[expanded_mask]

    def _deduplicate(self) -> None:
        """
        Keep only the most recent rollouts for each question.

        If the same question appears multiple times in the buffer,
        we keep only the most recent occurrence (latest addition).
        This prevents the buffer from being dominated by repeated questions.

        Implementation:
        - Scan from end to beginning (most recent first)
        - Keep first occurrence of each question index
        - Remove duplicates
        """
        if self.buffer is None or len(self.buffer) == 0:
            return

        indices = self.buffer.non_tensor_batch["index"]
        n_rollouts = len(indices)
        n_questions = n_rollouts // self.group_size

        # Get question-level indices (one per group)
        group_indices = [indices[i * self.group_size] for i in range(n_questions)]

        # Find last occurrence of each unique index (scanning from end)
        last_occurrence = {}
        for i, idx in enumerate(group_indices):
            last_occurrence[idx] = i  # Overwrites, so keeps last

        # Build mask: True for rollouts in groups we want to keep
        keep_groups = set(last_occurrence.values())
        mask = []
        for i in range(n_questions):
            keep = i in keep_groups
            mask.extend([keep] * self.group_size)

        mask = torch.tensor(mask, dtype=torch.bool)

        if mask.sum() < len(self.buffer):
            self.buffer = self.buffer[mask]

    def _truncate_to_capacity(self) -> None:
        """
        FIFO truncation: remove oldest entries if over capacity.

        We keep the most recent `capacity` question-groups,
        discarding the oldest ones (at the front of the buffer).
        """
        if self.buffer is None:
            return

        current_questions = len(self)
        if current_questions <= self.capacity:
            return

        # Keep last `capacity` question-groups
        keep_rollouts = self.capacity * self.group_size
        self.buffer = self.buffer[-keep_rollouts:]

    def sample(self, num_samples: int) -> Optional[DataProto]:
        """
        Sample question-groups from the buffer for replay.

        Args:
            num_samples: Number of questions to sample (not rollouts).
                        Will return num_samples * group_size rollouts.

        Returns:
            DataProto containing sampled rollouts, or None if buffer
            doesn't have enough samples.

        Example:
            >>> # Need (1-delta)*B questions from replay
            >>> n_replay = int((1 - 0.5) * 8)  # 4 questions
            >>> replay_batch = buffer.sample(n_replay)
            >>> if replay_batch is not None:
            ...     combined = DataProto.concat([fresh, replay_batch])
        """
        if self.buffer is None or len(self) < num_samples:
            return None

        n_questions = len(self)

        if self.replay_strategy == "random":
            # Random selection without replacement
            selected_questions = torch.randperm(n_questions)[:num_samples].tolist()

        elif self.replay_strategy == "fifo":
            # Oldest first (front of buffer)
            selected_questions = list(range(num_samples))

        else:
            raise ValueError(f"Unknown replay strategy: {self.replay_strategy}")

        # Convert question indices to rollout indices
        rollout_indices = []
        for q_idx in selected_questions:
            start = q_idx * self.group_size
            rollout_indices.extend(range(start, start + self.group_size))

        return self.buffer[rollout_indices]

    def clear(self) -> None:
        """Clear all data from the buffer."""
        self.buffer = None
        self._question_indices = {}

    def save(self, path: str) -> None:
        """
        Save buffer to disk.

        Useful for checkpointing during long training runs.

        Args:
            path: File path to save to (e.g., "replay_buffer.pkl")
        """
        if self.buffer is not None:
            self.buffer.save_to_disk(path)

    def load(self, path: str, device: str = "cpu") -> None:
        """
        Load buffer from disk.

        Args:
            path: File path to load from
            device: Device to load tensors to
        """
        self.buffer = DataProto.load_from_disk(path, device)

    def get_stats(self) -> Dict:
        """
        Get buffer statistics for logging.

        Returns:
            Dictionary with buffer statistics
        """
        if self.buffer is None:
            return {
                "num_questions": 0,
                "num_rollouts": 0,
                "capacity_used": 0.0,
            }

        rewards = self.buffer.batch.get("rewards", None)
        avg_reward = rewards.mean().item() if rewards is not None else None

        return {
            "num_questions": len(self),
            "num_rollouts": self.num_rollouts,
            "capacity_used": len(self) / self.capacity,
            "avg_reward": avg_reward,
        }

    def __repr__(self) -> str:
        stats = self.get_stats()
        return (
            f"ReplayBuffer("
            f"questions={stats['num_questions']}/{self.capacity}, "
            f"rollouts={stats['num_rollouts']}, "
            f"strategy={self.replay_strategy})"
        )


def combine_fresh_and_replay(
    fresh_batch: DataProto,
    replay_buffer: ReplayBuffer,
    delta: float,
    batch_size: int
) -> Tuple[DataProto, bool]:
    """
    Combine fresh rollouts with replayed rollouts.

    This is the core RR (Rollout Replay) operation:
    - Fresh rollouts: δ·B questions (newly generated)
    - Replay rollouts: (1-δ)·B questions (from buffer)
    - Combined: B questions total

    Args:
        fresh_batch: DataProto with freshly generated rollouts
        replay_buffer: ReplayBuffer to sample from
        delta: Fresh rollout fraction (0 < δ <= 1)
        batch_size: Total batch size B (in questions)

    Returns:
        Tuple of:
        - combined DataProto (fresh + replay)
        - bool indicating if replay was used (False if buffer not ready)

    Example:
        >>> fresh = generate_rollouts(selected_questions, ...)
        >>> combined, used_replay = combine_fresh_and_replay(
        ...     fresh, buffer, delta=0.5, batch_size=8
        ... )
        >>> # combined has 8 questions (4 fresh + 4 replay)
    """
    n_replay = int((1 - delta) * batch_size)

    if n_replay == 0 or not replay_buffer.is_ready(n_replay):
        # No replay needed or buffer not ready
        return fresh_batch, False

    # Sample from replay buffer
    replay_batch = replay_buffer.sample(n_replay)

    if replay_batch is None:
        return fresh_batch, False

    # Combine fresh and replay
    combined = DataProto.concat([fresh_batch, replay_batch])

    return combined, True


# Example usage and testing
if __name__ == "__main__":
    print("Testing ReplayBuffer...")

    # Create buffer
    buffer = ReplayBuffer(capacity=4, group_size=2, filter_informative=True)
    print(f"Empty buffer: {buffer}")

    # Create sample rollout data
    def make_rollout_batch(question_ids: List[int], rewards_per_q: List[List[float]]):
        """Helper to create test rollout data."""
        n_questions = len(question_ids)
        group_size = len(rewards_per_q[0])
        n_rollouts = n_questions * group_size

        # Flatten rewards
        flat_rewards = []
        for r_list in rewards_per_q:
            flat_rewards.extend(r_list)

        # Expand question IDs for each rollout
        flat_indices = []
        flat_questions = []
        flat_solutions = []
        for i, qid in enumerate(question_ids):
            flat_indices.extend([qid] * group_size)
            flat_questions.extend([f"Question {qid}"] * group_size)
            flat_solutions.extend([f"Solution {qid}"] * group_size)

        return DataProto(
            batch={
                "input_ids": torch.randint(0, 100, (n_rollouts, 10)),
                "old_log_probs": torch.randn(n_rollouts, 10),
                "rewards": torch.tensor(flat_rewards),
                "advantages": torch.tensor(flat_rewards) - torch.tensor(flat_rewards).mean(),
            },
            non_tensor_batch={
                "index": flat_indices,
                "question": flat_questions,
                "solution": flat_solutions,
            }
        )

    # Test 1: Add informative samples
    print("\n--- Test 1: Adding informative samples ---")
    batch1 = make_rollout_batch(
        question_ids=[0, 1],
        rewards_per_q=[[1.0, 0.0], [1.0, 1.0]]  # Q0: informative, Q1: not informative
    )
    added = buffer.add(batch1)
    print(f"Added {added} questions (expected 1, Q1 filtered out)")
    print(f"Buffer: {buffer}")

    # Test 2: Add more and test deduplication
    print("\n--- Test 2: Deduplication ---")
    batch2 = make_rollout_batch(
        question_ids=[0, 2],  # Q0 is duplicate, Q2 is new
        rewards_per_q=[[0.0, 1.0], [1.0, 0.0]]  # Both informative
    )
    buffer.add(batch2)
    print(f"After adding Q0 (dup) and Q2: {buffer}")
    # Q0 should be deduplicated (keep most recent)

    # Test 3: Sampling
    print("\n--- Test 3: Sampling ---")
    sample = buffer.sample(num_samples=1)
    if sample:
        print(f"Sampled 1 question: indices={sample.non_tensor_batch['index'][:2]}")

    # Test 4: FIFO truncation
    print("\n--- Test 4: FIFO truncation ---")
    for i in range(3, 10):
        batch = make_rollout_batch(
            question_ids=[i],
            rewards_per_q=[[1.0, 0.0]]
        )
        buffer.add(batch)
    print(f"After adding many: {buffer}")
    print(f"Should be at capacity ({buffer.capacity})")

    # Test 5: combine_fresh_and_replay
    print("\n--- Test 5: Combine fresh and replay ---")
    fresh = make_rollout_batch(
        question_ids=[100, 101],
        rewards_per_q=[[1.0, 0.0], [0.0, 1.0]]
    )
    combined, used_replay = combine_fresh_and_replay(
        fresh, buffer, delta=0.5, batch_size=4
    )
    print(f"Fresh: 2 questions, Combined: {len(combined)//2} questions")
    print(f"Used replay: {used_replay}")

    print("\nAll tests passed!")
