"""
Rollout Generation for GRPO Training

This module handles generating completions (rollouts) from the policy model
and packaging them into DataProto format for training.

Key Concepts:
=============

1. WHAT IS A ROLLOUT?
   A rollout is a single completion generated by the model for a given prompt.
   For GRPO, we generate G rollouts per question to:
   - Estimate difficulty: d_q = 1 - mean(rewards)
   - Compute group-relative advantages: A_i = r_i - mean(r)

2. WHY MULTIPLE ROLLOUTS?
   With G=1, advantage would be A = r - r = 0 (no gradient signal).
   With G>1, we get variance in rewards → meaningful advantages.
   Paper uses G=8.

3. WHAT TO STORE?
   For each rollout, we need:
   - input_ids: Full sequence (prompt + generated response)
   - response_ids: Just the generated part
   - attention_mask: For proper attention computation
   - old_log_probs: π_old(response | prompt) - CRITICAL for GRPO ratio
   - rewards: Binary reward (0 or 1)
   - advantages: Group-normalized advantage

4. OLD_LOG_PROBS - WHY CRITICAL?
   GRPO computes the ratio: π_θ(a|s) / π_old(a|s)

   - π_θ: Current policy (computed during training forward pass)
   - π_old: Policy that generated the rollout (stored as old_log_probs)

   For fresh rollouts: π_old = current model at rollout time
   For replayed rollouts: π_old = model from when rollout was generated

   This is what makes replay "off-policy" - the rollout was generated
   by a different (older) policy than the current one.

5. EFFICIENCY
   - Batch all G rollouts together (repeat prompt G times)
   - Use sampling (do_sample=True) for diversity
   - Generate all rollouts for a question in one forward pass

Reference:
    verl rollout generation: verl/workers/rollout/
"""

import torch
import torch.nn.functional as F
from typing import List, Tuple, Optional, Dict, Any
from dataclasses import dataclass

from data_proto import DataProto, create_rollout_data
from reward_functions import compute_reward, compute_difficulty_from_rewards, is_informative


# Prompt template matching the paper's setup
SYSTEM_PROMPT = "Let's think step by step and output the final answer within \\boxed{}."

def format_prompt(question: str) -> str:
    """
    Format a question into a chat prompt.

    Args:
        question: Raw question text

    Returns:
        Formatted prompt string
    """
    # Simple format - models like Qwen use chat templates
    return f"{SYSTEM_PROMPT}\n\n{question}"


def apply_chat_template(
    question: str,
    tokenizer,
    add_generation_prompt: bool = True
) -> Dict[str, torch.Tensor]:
    """
    Apply chat template to format the prompt.

    Args:
        question: Question text
        tokenizer: HuggingFace tokenizer with chat template
        add_generation_prompt: Whether to add generation prompt

    Returns:
        Dictionary with input_ids and attention_mask
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question}
    ]

    # Use tokenizer's chat template if available
    if hasattr(tokenizer, 'apply_chat_template'):
        text = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=add_generation_prompt,
            tokenize=False
        )
        encoded = tokenizer(text, return_tensors="pt")
    else:
        # Fallback for tokenizers without chat template
        prompt = format_prompt(question)
        encoded = tokenizer(prompt, return_tensors="pt")

    return encoded


@torch.no_grad()
def generate_rollouts_for_question(
    question: str,
    tokenizer,
    model,
    num_rollouts: int = 8,
    max_new_tokens: int = 1024,
    temperature: float = 0.6,
    top_p: float = 0.95,
) -> Tuple[List[str], torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Generate G rollouts for a single question.

    Args:
        question: Question text
        tokenizer: HuggingFace tokenizer
        model: HuggingFace causal LM
        num_rollouts: G - number of rollouts to generate
        max_new_tokens: Maximum tokens to generate
        temperature: Sampling temperature
        top_p: Top-p sampling threshold

    Returns:
        Tuple of:
        - completions: List of G completion strings
        - response_ids: [G, max_response_len] token IDs
        - log_probs: [G, max_response_len] per-token log probs
        - attention_mask: [G, max_response_len] mask
    """
    # Encode prompt
    encoded = apply_chat_template(question, tokenizer)
    prompt_ids = encoded["input_ids"].to(model.device)
    prompt_len = prompt_ids.shape[1]

    # Repeat prompt G times for batch generation
    batch_input_ids = prompt_ids.repeat(num_rollouts, 1)
    batch_attention_mask = torch.ones_like(batch_input_ids)

    # Generate
    outputs = model.generate(
        batch_input_ids,
        attention_mask=batch_attention_mask,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=temperature,
        top_p=top_p,
        pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
        return_dict_in_generate=True,
        output_scores=True,  # Need scores for log_probs
    )

    # Extract generated sequences
    generated_ids = outputs.sequences  # [G, prompt_len + response_len]

    # Get response-only IDs
    response_ids = generated_ids[:, prompt_len:]  # [G, response_len]

    # Decode completions
    completions = [
        tokenizer.decode(response_ids[i], skip_special_tokens=True)
        for i in range(num_rollouts)
    ]

    # Compute log probabilities for the generated tokens
    # This is π_old(response | prompt) - needed for GRPO ratio
    log_probs = compute_log_probs_from_scores(outputs.scores, response_ids)

    # Create attention mask for responses
    response_attention_mask = (response_ids != tokenizer.pad_token_id).long()

    return completions, response_ids, log_probs, response_attention_mask


def compute_log_probs_from_scores(
    scores: Tuple[torch.Tensor, ...],
    token_ids: torch.Tensor
) -> torch.Tensor:
    """
    Compute log probabilities from generation scores.

    Args:
        scores: Tuple of [batch, vocab] logit tensors, one per generated token
        token_ids: [batch, seq_len] generated token IDs

    Returns:
        log_probs: [batch, seq_len] log probabilities
    """
    batch_size = token_ids.shape[0]
    seq_len = len(scores)

    log_probs = torch.zeros(batch_size, seq_len, device=token_ids.device)

    for t, score in enumerate(scores):
        # score: [batch, vocab]
        log_p = F.log_softmax(score, dim=-1)
        # Get log prob of the actual token generated
        token_log_p = log_p.gather(1, token_ids[:, t:t+1]).squeeze(1)
        log_probs[:, t] = token_log_p

    return log_probs


@torch.no_grad()
def compute_log_probs_for_response(
    prompt_ids: torch.Tensor,
    response_ids: torch.Tensor,
    model,
    attention_mask: Optional[torch.Tensor] = None
) -> torch.Tensor:
    """
    Compute log probabilities for a response given a prompt.

    This is used to get π_θ(response | prompt) during training,
    where θ is the current policy parameters.

    Args:
        prompt_ids: [batch, prompt_len] prompt token IDs
        response_ids: [batch, response_len] response token IDs
        model: HuggingFace causal LM
        attention_mask: Optional attention mask

    Returns:
        log_probs: [batch, response_len] per-token log probabilities
    """
    batch_size = prompt_ids.shape[0]
    prompt_len = prompt_ids.shape[1]

    # Concatenate prompt and response
    input_ids = torch.cat([prompt_ids, response_ids], dim=1)

    if attention_mask is None:
        attention_mask = torch.ones_like(input_ids)

    # Forward pass
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
    logits = outputs.logits  # [batch, seq_len, vocab]

    # Get logits for response positions (shifted by 1 for autoregressive)
    # Position i predicts token i+1
    response_logits = logits[:, prompt_len-1:-1, :]  # [batch, response_len, vocab]

    # Compute log probabilities
    log_probs = F.log_softmax(response_logits, dim=-1)

    # Get log prob of actual response tokens
    response_log_probs = log_probs.gather(
        2, response_ids.unsqueeze(-1)
    ).squeeze(-1)  # [batch, response_len]

    return response_log_probs


def compute_advantages(
    rewards: torch.Tensor,
    group_size: int,
    normalize_by_std: bool = False
) -> torch.Tensor:
    """
    Compute group-relative advantages for GRPO.

    For each question with G rollouts:
        A_i = r_i - mean(r_1, ..., r_G)

    Optionally normalize by std (but Dr. GRPO recommends against this).

    Args:
        rewards: [N * G] flat tensor of rewards
        group_size: G - number of rollouts per question
        normalize_by_std: Whether to divide by std (default False per Dr. GRPO)

    Returns:
        advantages: [N * G] tensor of advantages
    """
    n_questions = rewards.shape[0] // group_size

    # Reshape to [N, G]
    rewards_grouped = rewards.view(n_questions, group_size)

    # Compute mean per group
    group_means = rewards_grouped.mean(dim=1, keepdim=True)  # [N, 1]

    # Advantages = reward - group mean
    advantages = rewards_grouped - group_means  # [N, G]

    if normalize_by_std:
        group_stds = rewards_grouped.std(dim=1, keepdim=True).clamp(min=1e-8)
        advantages = advantages / group_stds

    return advantages.view(-1)  # Flatten back to [N * G]


@dataclass
class RolloutBatch:
    """
    Container for a batch of rollouts.

    Attributes:
        input_ids: [batch, seq_len] full sequences
        attention_mask: [batch, seq_len]
        response_ids: [batch, response_len] response only
        old_log_probs: [batch, response_len] log probs at generation time
        rewards: [batch] binary rewards
        advantages: [batch] group-normalized advantages
        indices: List of question indices
        questions: List of question strings
        solutions: List of solution strings
    """
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    response_ids: torch.Tensor
    old_log_probs: torch.Tensor
    rewards: torch.Tensor
    advantages: torch.Tensor
    indices: List[int]
    questions: List[str]
    solutions: List[str]


def generate_rollout_batch(
    questions: List[str],
    solutions: List[str],
    indices: List[int],
    tokenizer,
    model,
    num_rollouts: int = 8,
    max_new_tokens: int = 1024,
    temperature: float = 0.6,
    top_p: float = 0.95,
    pad_to_max_length: bool = True,
    max_response_length: int = 1024,
) -> DataProto:
    """
    Generate rollouts for a batch of questions and package into DataProto.

    This is the main function for rollout generation in the training loop.

    Args:
        questions: List of N question strings
        solutions: List of N solution strings
        indices: List of N question indices (for tracking)
        tokenizer: HuggingFace tokenizer
        model: HuggingFace causal LM
        num_rollouts: G - rollouts per question
        max_new_tokens: Max tokens to generate
        temperature: Sampling temperature
        top_p: Top-p threshold
        pad_to_max_length: Whether to pad responses to same length
        max_response_length: Max response length for padding

    Returns:
        DataProto containing all rollout data (N * G rollouts total)
    """
    all_completions = []
    all_response_ids = []
    all_log_probs = []
    all_attention_masks = []
    all_rewards = []
    expanded_indices = []
    expanded_questions = []
    expanded_solutions = []

    model.eval()

    for i, (question, solution, idx) in enumerate(zip(questions, solutions, indices)):
        # Generate G rollouts
        completions, response_ids, log_probs, attn_mask = generate_rollouts_for_question(
            question=question,
            tokenizer=tokenizer,
            model=model,
            num_rollouts=num_rollouts,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=top_p,
        )

        # Compute rewards
        rewards = [compute_reward(c, solution) for c in completions]

        all_completions.extend(completions)
        all_response_ids.append(response_ids)
        all_log_probs.append(log_probs)
        all_attention_masks.append(attn_mask)
        all_rewards.extend(rewards)

        # Expand metadata for each rollout
        expanded_indices.extend([idx] * num_rollouts)
        expanded_questions.extend([question] * num_rollouts)
        expanded_solutions.extend([solution] * num_rollouts)

    # Pad and stack tensors
    response_ids = pad_sequences(all_response_ids, tokenizer.pad_token_id or 0)
    log_probs = pad_sequences(all_log_probs, 0.0)
    attention_masks = pad_sequences(all_attention_masks, 0)

    rewards = torch.tensor(all_rewards, dtype=torch.float32)

    # Compute advantages
    advantages = compute_advantages(rewards, num_rollouts, normalize_by_std=False)

    # Create DataProto
    data = DataProto(
        batch={
            "response_ids": response_ids,
            "old_log_probs": log_probs,
            "attention_mask": attention_masks,
            "rewards": rewards,
            "advantages": advantages,
        },
        non_tensor_batch={
            "index": expanded_indices,
            "question": expanded_questions,
            "solution": expanded_solutions,
            "completion": all_completions,
        },
        meta_info={
            "num_questions": len(questions),
            "num_rollouts": num_rollouts,
        }
    )

    return data


def pad_sequences(
    sequences: List[torch.Tensor],
    pad_value: float = 0.0
) -> torch.Tensor:
    """
    Pad a list of variable-length tensors to the same length.

    Args:
        sequences: List of [G, varying_len] tensors
        pad_value: Value to use for padding

    Returns:
        Padded tensor [total_batch, max_len]
    """
    # Concatenate all sequences
    all_seqs = torch.cat(sequences, dim=0)

    # Already same length within each batch, so just return
    return all_seqs


def filter_informative_rollouts(
    data: DataProto,
    group_size: int
) -> DataProto:
    """
    Filter to keep only informative question-groups.

    A question is informative if its rollouts have mixed rewards.

    Args:
        data: DataProto with rollouts
        group_size: Number of rollouts per question

    Returns:
        Filtered DataProto
    """
    rewards = data.batch["rewards"]
    n_rollouts = len(rewards)
    n_questions = n_rollouts // group_size

    # Check each question group
    informative_mask = []
    for q in range(n_questions):
        start = q * group_size
        end = start + group_size
        group_rewards = rewards[start:end].tolist()

        if is_informative(group_rewards):
            informative_mask.extend([True] * group_size)
        else:
            informative_mask.extend([False] * group_size)

    mask = torch.tensor(informative_mask, dtype=torch.bool)

    if mask.sum() == 0:
        return DataProto()  # Empty

    return data[mask]


# Example usage
if __name__ == "__main__":
    print("Rollout generation module loaded.")
    print("\nKey functions:")
    print("  - generate_rollouts_for_question(): Generate G rollouts for one question")
    print("  - generate_rollout_batch(): Generate rollouts for a batch of questions")
    print("  - compute_advantages(): Compute GRPO advantages")
    print("  - filter_informative_rollouts(): Filter for informative samples")

    print("\n--- Test: compute_advantages ---")
    # Test with known rewards
    rewards = torch.tensor([1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0])
    advantages = compute_advantages(rewards, group_size=4)
    print(f"Rewards: {rewards.tolist()}")
    print(f"Advantages: {advantages.tolist()}")
    # Expected: Q1 mean=0.5, Q2 mean=0.25
    # Q1 advantages: [0.5, 0.5, -0.5, -0.5]
    # Q2 advantages: [0.75, -0.25, -0.25, -0.25]
